/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { StakingPool } from "./StakingPool";
export * as factories from "./factories";
export { StakingPool__factory } from "./factories/StakingPool__factory";
